---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/develop?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    password: xlfldpf321!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/static/
  mvc:
    view:
      suffix: .html
server:
  port: 8090

---

spring:
  config:
    activate:
      on-profile: ubuntu
  datasource:
    username: postgres
    #url: jdbc:postgresql://192.168.0.227:5432/postgres
    url: jdbc:postgresql://182.211.204.237:5432/postgres
    driverClassName: org.postgresql.Driver
    password: xlfldpf1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none
  thymeleaf:
    prefix: classpath:/static/
  mvc:
    view:
      suffix: .html
server:
  port: 8090

---

spring:
  config:
    activate:
      on-profile: home
  datasource:
    username: postgres
    url: jdbc:postgresql://182.211.204.237:5432/postgres
    driverClassName: org.postgresql.Driver
    password: xlfldpf1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none
  thymeleaf:
    prefix: classpath:/static/
  mvc:
    view:
      suffix: .html
server:
  port: 8090

